name: ci

env:
  CTEST_PARALLEL_LEVEL: 2
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - "CMakePresets.json"
      - "cmake/libraries.json"
      - "!cmake/intel.cmake"
      - ".github/workflows/ci.yml"
# paths ignore starting with "!"
      - "!docs/**"
      - "!**/cray.cmake"


jobs:

  core:
    timeout-minutes: 30

    strategy:
      matrix:
        # hwm14: [true, false]
        hwm14: [false]
        # TODO: temp workaround for fclaw_prep3
        img: [{os: ubuntu-latest, cc: gcc-9, cxx: g++-9, fc: gfortran-9},
              {os: ubuntu-latest, cc: gcc-10, cxx: g++-10, fc: gfortran-10},
              {os: ubuntu-latest, cc: gcc-11, cxx: g++-11, fc: gfortran-11},
              {os: ubuntu-latest, cc: gcc-12, cxx: g++-12, fc: gfortran-12},
              {os: macos-latest, cc: clang, cxx: clang++, fc: gfortran-12}]

    env:
      CC: ${{ matrix.img.cc }}
      CXX: ${{ matrix.img.cxx }}
      FC: ${{ matrix.img.fc }}

    runs-on: ${{ matrix.img.os }}

    steps:

    - name: Checkout Gemini3D-External
      uses: actions/checkout@v3
      with:
        repository: gemini3d/external
        path: gemext

    - name: Install packages (Linux)
      if: runner.os == 'Linux'
      timeout-minutes: 15
      run: |
        sudo $(cmake -P gemext/scripts/requirements.cmake) ninja-build liblapack-dev libscalapack-mpi-dev

    - name: Install packages (MacOS)
      if: runner.os == 'macOS'
      timeout-minutes: 15
      run: |
        $(cmake -P gemext/scripts/requirements.cmake)
        brew install ninja scalapack

    - name: Install model libraries
      timeout-minutes: 15
      run: |
        cmake -Bbuild -GNinja -Dfind:BOOL=true -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}
        cmake --build build
        cmake --install build
      working-directory: gemext

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - uses: actions/checkout@v3

    - name: Configure multi
      run: >-
        cmake --preset multi
        -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }}
        -Dhwm14:BOOL=${{ matrix.hwm14 }}

    - name: Debug build
      run: cmake --build --preset debug

    - name: Debug unit test
      run: ctest --preset debug -L unit

    # - name: Debug core test
    #   run: ctest --preset debug -LE unit -R "(2dew_.*fang|2dns_.*fang)"


    - name: Release build
      run: cmake --build --preset release

    - name: Release unit test
      run: ctest --preset release -L unit

    # - name: Release core test
    #   run: ctest --preset release -LE unit -E 3d
